DROP TABLE IF EXISTS `bookings`;
DROP TABLE IF EXISTS `shows`;
DROP TABLE IF EXISTS `movies`;
DROP TABLE IF EXISTS `halls`;
DROP TABLE IF EXISTS `theatres`;
DROP TABLE IF EXISTS `regions`;
DROP TABLE IF EXISTS `timings`;
DROP TABLE IF EXISTS `users`;